# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 22:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_order', models.IntegerField(default=0)),
                ('ability_name', models.CharField(default='', max_length=50)),
                ('heroid', models.IntegerField(default=0)),
                ('ability_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ('created_order',),
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=50)),
                ('localized_name', models.CharField(default='', max_length=50)),
                ('primary_attr', models.CharField(default='', max_length=3)),
                ('attack_type', models.CharField(default='o', max_length=6)),
                ('roles', django.contrib.postgres.fields.jsonb.JSONField()),
                ('webm', models.CharField(default='', max_length=100)),
                ('img', models.CharField(default='', max_length=100)),
                ('icon', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('base_health', models.IntegerField(default=0)),
                ('base_health_regen', models.FloatField(default=0.0)),
                ('base_mana', models.IntegerField(default=0)),
                ('base_mana_regen', models.FloatField(default=0.0)),
                ('base_armor', models.IntegerField(default=0)),
                ('base_mr', models.IntegerField(default=0)),
                ('base_attack_min', models.IntegerField(default=0)),
                ('base_attack_max', models.IntegerField(default=0)),
                ('base_str', models.IntegerField(default=0)),
                ('base_agi', models.IntegerField(default=0)),
                ('base_int', models.IntegerField(default=0)),
                ('str_gain', models.FloatField(default=0.0)),
                ('agi_gain', models.FloatField(default=0.0)),
                ('int_gain', models.FloatField(default=0.0)),
                ('attack_range', models.IntegerField(default=0)),
                ('projectile_speed', models.IntegerField(default=0)),
                ('attack_rate', models.FloatField(default=0.0)),
                ('move_speed', models.IntegerField(default=0)),
                ('turn_rate', models.FloatField(default=0.0)),
                ('cm_enabled', models.BooleanField(default=True)),
                ('legs', models.IntegerField(default=0)),
                ('complexity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='heroes.Hero'),
        ),
    ]
