# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='attack_type',
            field=models.CharField(default='', max_length=6),
        ),
    ]
