# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-16 22:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('marketcap', models.IntegerField(default=0)),
                ('open_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('time_series_daily', django.contrib.postgres.fields.jsonb.JSONField()),
                ('financials', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
