# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-19 21:09
from __future__ import unicode_literals

import collections
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180319_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time_series_daily',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=collections.OrderedDict),
        ),
    ]
