# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 23:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20180319_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='financials',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='time_series_daily',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
